CREATE TABLE COPA.EQUIPO(
NRO_EQUIPO VARCHAR(1),
NOMBRE_EQUIPO VARCHAR(20) NOT NULL,
CONSTRAINT PK_EQUIPO PRIMARY KEY(NRO_EQUIPO));

SELECT * FROM COPA.EQUIPO;

CREATE TABLE COPA.JUGADOR(
ID_JUGADOR VARCHAR(3),
NOMBRE_JUGADOR VARCHAR(40) NOT NULL,
NRO_EQUIPO VARCHAR(1),
CONSTRAINT PK_JUGADOR PRIMARY KEY(ID_JUGADOR),
CONSTRAINT FK_EQUIPO_JUGADOR FOREIGN KEY (NRO_EQUIPO)
REFERENCES COPA.EQUIPO (NRO_EQUIPO) ON UPDATE CASCADE ON DELETE CASCADE);

SELECT * FROM COPA.JUGADOR;


INSERT INTO COPA.EQUIPO (NRO_EQUIPO,NOMBRE_EQUIPO)
VALUES ('1','COLOMBIA'),
       ('2','BRASIL'),
	   ('3','ARGENTINA');
	   
	   
INSERT INTO COPA.JUGADOR (ID_JUGADOR,NOMBRE_JUGADOR,NRO_EQUIPO)
VALUES ('1','JAMES','1'),
       ('2','CUADRADO','1'),
	   ('3','NEYMAR','2'),
	   ('4','CASEMIRO','2'),
	   ('5','MESSI','3'),
	   ('6','AGUERO','3');
	   

CREATE TABLE COPA.AUDI_EQUIPO
(CONSECUTIVO SERIAL,
NRO_EQUIPO VARCHAR(1),
NOMBRE_EQUIPO VARCHAR(20) NOT NULL,
FECHA_REGISTRO TIMESTAMP,
USUARIO VARCHAR(20),
ACCION CHAR(1),
CONSTRAINT PK_AUDI_EQUIPO PRIMARY KEY (CONSECUTIVO)
);

SELECT * FROM COPA.AUDI_EQUIPO;

--TRIGGER
CREATE FUNCTION COPA.AUDI_EQUIPO_FUNC() RETURNS TRIGGER AS $TRG_GRABAR_AUDI_EQUIPO$
DECLARE
BEGIN
IF (TG_OP='UPDATE') THEN
INSERT INTO COPA.AUDI_EQUIPO(CONSECUTIVO,NRO_EQUIPO,NOMBRE_EQUIPO,FECHA_REGISTRO,USUARIO,ACCION)
VALUES (DEFAULT,OLD.NRO_EQUIPO,OLD.NOMBRE_EQUIPO,CURRENT_TIMESTAMP(0),CURRENT_USER,'U');
RETURN NEW;
ELSEIF (TG_OP='DELETE') THEN
INSERT INTO COPA.AUDI_EQUIPO(CONSECUTIVO,NRO_EQUIPO,NOMBRE_EQUIPO,FECHA_REGISTRO,USUARIO,ACCION)
VALUES(DEFAULT,OLD.NRO_EQUIPO,OLD.NOMBRE_EQUIPO,CURRENT_TIMESTAMP(0),CURRENT_USER,'D');
RETURN OLD;

END IF;
END;
$TRG_GRABAR_AUDI_EQUIPO$ LANGUAGE PLPGSQL;


--CREATE TRIGGER
CREATE TRIGGER TRG_GRABAR_AUDI_EQUIPO BEFORE UPDATE OR DELETE ON COPA.EQUIPO
	FOR EACH ROW EXECUTE PROCEDURE COPA.AUDI_EQUIPO_FUNC();
	
	
SELECT * FROM COPA.EQUIPO;
SELECT * FROM COPA.AUDI_EQUIPO;
SELECT * FROM COPA.JUGADOR;

DELETE FROM COPA.EQUIPO
WHERE NRO_EQUIPO = '3'; 

UPDATE COPA.EQUIPO SET NRO_EQUIPO= '5'
WHERE NRO_EQUIPO = '1';