SELECT * FROM ESCUELA.ESTUDIANTE;
SELECT * FROM ESCUELA.CURSO;

--CON JOINS 
SELECT ES.NOMBRE AS ESTUDIANTE, CU.NOMBRE AS CURSO
FROM ESCUELA.ESTUDIANTE ES INNER JOIN ESCUELA.CURSO CU
ON ES.CURSO = CU.CURSO;

SELECT ES.NOMBRE AS ESTUDIANTE, CU.NOMBRE AS CURSO
FROM ESCUELA.ESTUDIANTE ES LEFT JOIN ESCUELA.CURSO CU
ON ES.CURSO = CU.CURSO;

SELECT ES.NOMBRE AS ESTUDIANTE, CU.NOMBRE AS CURSO
FROM ESCUELA.ESTUDIANTE ES LEFT JOIN ESCUELA.CURSO CU
ON ES.CURSO = CU.CURSO
WHERE CU.CURSO IS NULL;

SELECT FA.CONSECUTIVO AS FACTURA, EM.NOMBRE AS EMPLEADO
FROM TIENDA.CLIENTE CL INNER JOIN TIENDA.FACTURA FA
ON CL.DOCUMENTO = FA.DOCUMENTO
INNER JOIN TIENDA.EMPLEADO EM
ON FA.COD_EMPLEADO = EM.COD_EMPLEADO
WHERE CL.SEXO = 'F'
AND FA.FECHA BETWEEN '01/01/2024' AND '31/12/2024';

SELECT EM.NOMBRE AS EMPLEADO, MP.NOM_MPIO AS MUNICIPIO
FROM TIENDA.EMPLEADO EM INNER JOIN TIENDA.MPIO MP
ON EM.COD_PAIS_NTO = MP.COD_PAIS
AND EM.COD_DPTO_NTO = MP.COD_DPTO
AND EM.COD_MPIO_NTO = MP.COD_MPIO
INNER JOIN TIENDA.DPTO DP
ON MP.COD_PAIS = DP.COD_PAIS
AND MP.COD_DPTO = DP.COD_DPTO
WHERE DP.NOM_DPTO='SANTANDER'
ORDER BY 2;

--REUNIONES
SELECT ES.NOMBRE AS ESTUDIANTE,CU.NOMBRE AS CURSO
FROM ESCUELA.ESTUDIANTE ES, ESCUELA.CURSO CU
WHERE ES.CURSO = CU.CURSO


