--LISTAR EL TOTAL DE LAS VENTAS REALIZADAS POR AÑO,
--DONDE EL TOTAL DE LAS VENTAS SEA MAYOR A 1000.000.000
--ORDENAR DE FORMA DESCENDENTE POR EL AÑO 

--AGRUPAR, COLOCAR EL MISMO ATRIVUTO QUE SE ESTÁ USANDO
SELECT EXTRACT(YEAR FROM FECHA) AS YEAR, SUM(TOTAL) AS TOTAL_VENTAS
FROM TIENDA.FACTURA
GROUP BY EXTRACT(YEAR FROM FECHA) 
HAVING SUM (TOTAL) > 1000000000
ORDER BY 1 DESC
LIMIT 4;


--LISTAR EL NOMBRE DE LOS BARRIOS Y LA CANTIDAD DE CLIENTES POR BARRIO
SELECT B.NOMBRE AS BARRIO, COUNT(*) AS CANTIDAD_CLIENTES
FROM TIENDA.BARRIO B INNER JOIN TIENDA.CLIENTE CL
ON (B.COD_COMUNA = CL.COD_COMUNA)
AND (B.COD_BARRIO = CL.COD_BARRIO)
GROUP BY B.NOMBRE
HAVING COUNT(*) >= 30;


--LISTAR EL NOMBRE Y EL PRECIO DE LOS PRODUCTOS 
--QUE NUNCA SE HAN VENDIDO EN EL AÑO 2025
SELECT AR.DESCRIPCION, AR.VALOR
FROM TIENDA.ARTICULO AR
LEFT JOIN TIENDA.DETALLE D
ON AR.COD_ARTICULO = D.COD_ARTICULO 
INNER JOIN TIENDA.FACTURA F
ON D.CONSECUTIVO = F.CONSECUTIVO
WHERE D.COD_ARTICULO IS NULL
AND FECHA BETWEEN '01/01/2025' AND '31/12/2025'


--LISTAR EL NOMBRE DE LOS COLORES Y CUANTOS PRODUCTOS HAY POR COLOR 
--LA SALIDA DEBE MOSTRAR SOLO AQUELLOS COLORES SEAN MAYORES A 5
SELECT COLOR, COUNT(*) AS CANTIDAD
FROM TIENDA.ARTICULO
GROUP BY COLOR 
HAVING COUNT(*) > 5;