--SUBCONSULTAS

--LISTAR EL NOMBRE DE LOS EMPLEADOS, JUNTO CON LA CANTIDAD DE
--FACTURAS QUE HAN GESTIONADO. MOSTRAR SOLO LA CANTIDAD DE FACTURAS
--GESTIONADAS QUE SEAN MAYORES O IGUALES A LA CANTIDAD DE LAS FACTURAS
--GESTIONADAS POR EMPLEADOS DEL MUNICIPIO DE SANTANDER 
SELECT E.NOMBRE AS EMPLEADO,E.COD_DPTO_NTO,COUNT(*) AS TOTAL_FACTURAS
FROM TIENDA.EMPLEADO E INNER JOIN TIENDA.FACTURA F
ON E.COD_EMPLEADO = F.COD_EMPLEADO
GROUP BY E.NOMBRE,E.COD_DPTO_NTO 
HAVING COUNT(*) >=
	(SELECT COUNT(*)
	FROM TIENDA.EMPLEADO E INNER JOIN TIENDA.FACTURA F
	ON E.COD_EMPLEADO = F.COD_EMPLEADO
	INNER JOIN TIENDA.MPIO M
	ON M.COD_PAIS = E.COD_PAIS_NTO
	AND M.COD_DPTO = E.COD_DPTO_NTO
	AND M.COD_MPIO = E.COD_MPIO_NTO
	INNER JOIN TIENDA.DPTO D
	ON M.COD_PAIS = D.COD_PAIS
	AND M.COD_DPTO = D.COD_DPTO
	WHERE D.NOM_DPTO = 'SANTANDER')
	
	
--LISTAR EL NOMBRE DE LOS ARTICULOS QUE NUNCA SE HAYAN GESTIONADO EN UNA FACTURA 
SELECT DISTINCT A.DESCRIPCION 
FROM TIENDA.ARTICULO A LEFT JOIN TIENDA.DETALLE D
ON A.COD_ARTICULO = D.COD_ARTICULO 
WHERE D.COD_ARTICULO IS NULL;

SELECT DISTINCT A.DESCRIPCION AS ARTICULO 
FROM TIENDA.ARTICULO A
WHERE A.COD_ARTICULO NOT IN
	(SELECT DISTINCT D.COD_ARTICULO
	FROM TIENDA.DETALLE D);
	
SELECT DISTINCT A.DESCRIPCION AS ARTICULO 
FROM TIENDA.ARTICULO A
WHERE NOT EXISTS
	(SELECT DISTINCT D.COD_ARTICULO
	FROM TIENDA.DETALLE D
	WHERE A.COD_ARTICULO = D.COD_ARTICULO);
	
--LISTAR LAS FACTURAS DEL AÑO 2024 DONDE EL VALOR TOTAL, ES MAYOR QUE LA FACTURA CON
--MENOR VALOR DE LAS FACTURAS DEL AÑO 2025
SELECT F1.CONSECUTIVO,F1.TOTAL
FROM TIENDA.FACTURA F1
WHERE F1.FECHA BETWEEN '01/01/2024' AND '31/12/2024'
AND F1.TOTAL >
	(SELECT MIN(F2.TOTAL)  
	FROM TIENDA.FACTURA F2 
	WHERE F2.FECHA BETWEEN '01/01/2025' AND '31/12/2025')

SELECT * FROM TIENDA.FACTURA