CREATE TABLE TIENDA.USUARIO
(COD_USUARIO SERIAL,
NOMBRE_USUARIO VARCHAR(30),
CONTRASENA VARCHAR(20),
FECHA_CREACION TIMESTAMP,
ACTIVO BOOLEAN,
CONSTRAINT UC_NOMBRE_USUARIO UNIQUE(NOMBRE_USUARIO),
CONSTRAINT CK_CONTRASENA CHECK (CONTRASENA IS NOT NULL),
CONSTRAINT PK_COD_USUARIO PRIMARY KEY (COD_USUARIO)
);

SELECT * FROM TIENDA.USUARIO;