CREATE TABLE TIENDA.PUSUARIO
(USUARIO INTEGER,
NOMBRE_USUARIO VARCHAR(30),
CONTRASENA VARCHAR(20),
FECHA_CREACION TIMESTAMP,
ACTIVO BOOLEAN DEFAULT 'Y',
CONSTRAINT UC_NOMBREUSUARIO UNIQUE(NOMBRE_USUARIO),
CONSTRAINT NN_PASSWORD CHECK (CONTRASENA IS NOT NULL),
CONSTRAINT PK_PUSUARIO PRIMARY KEY (USUARIO)
);

SELECT * FROM TIENDA.PUSUARIO;

--CREACION DE SECUENCIA PARA QUE EL CODIGO EMPIECE EN 1000 (1001,1002)
CREATE SEQUENCE tienda.pusuario_seq START WITH 1000 INCREMENT BY 1;

SELECT * FROM tienda.pusuario_seq;

SELECT nextval('tienda.pusuario_seq');

SELECT * FROM TIENDA.PUSUARIO;