INSERT INTO TIENDA.PUSUARIO (USUARIO,NOMBRE_USUARIO,CONTRASENA,FECHA_CREACION,ACTIVO)
VALUES (nextval('tienda.pusuario_seq'),'PGARCIA','PAULAG','18/03/2025 11:15:00',DEFAULT);

SELECT * FROM TIENDA.PUSUARIO;
